//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLCARTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALLCARTYPE()
        {
            this.CARS = new HashSet<CAR>();
        }
    
        public string thisCarType { get; set; }
        public string carFirm { get; set; }
        public string carModel { get; set; }
        public decimal carDayPrice { get; set; }
        public decimal carLatePrice { get; set; }
        public int carYear { get; set; }
        public string carGear { get; set; }
        public int carTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR> CARS { get; set; }
    }
}
