//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARFORRENT
    {
        public System.DateTime rentStartDate { get; set; }
        public System.DateTime rentEndDate { get; set; }
        public Nullable<System.DateTime> rentRealEndDate { get; set; }
        public string userID { get; set; }
        public string carNumber { get; set; }
        public int rentNumber { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual USER USER { get; set; }
    }
}
