//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.EntityDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.CARFORRENTS = new HashSet<CARFORRENT>();
            this.MESSAGES = new HashSet<MESSAGE>();
        }
    
        public string userID { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userNickName { get; set; }
        public Nullable<System.DateTime> userBirthDate { get; set; }
        public string userGender { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public string userPicture { get; set; }
        public int userLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARFORRENT> CARFORRENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MESSAGE> MESSAGES { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
